# Generated by Django 5.2.4 on 2025-07-24 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='easy_going_count',
            field=models.IntegerField(default=0, help_text='Number of "easy going" ratings'),
        ),
        migrations.AddField(
            model_name='user',
            name='fleksibel_count',
            field=models.IntegerField(default=0, help_text='Number of "fleksibel" ratings'),
        ),
        migrations.AddField(
            model_name='user',
            name='informatif_count',
            field=models.IntegerField(default=0, help_text='Number of "informatif" ratings'),
        ),
        migrations.AddField(
            model_name='user',
            name='ramah_count',
            field=models.IntegerField(default=0, help_text='Number of "ramah" ratings'),
        ),
        migrations.AddField(
            model_name='user',
            name='seru_count',
            field=models.IntegerField(default=0, help_text='Number of "seru" ratings'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total number of people who rated this guide'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('guider', 'Tour Guide')], default='user', help_text='Role of the user - either user or guider', max_length=10),
        ),
        migrations.CreateModel(
            name='TourGuideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramah', models.BooleanField(default=False)),
                ('seru', models.BooleanField(default=False)),
                ('informatif', models.BooleanField(default=False)),
                ('fleksibel', models.BooleanField(default=False)),
                ('easy_going', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('tour_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Guide Rating',
                'verbose_name_plural': 'Tour Guide Ratings',
                'unique_together': {('rater', 'tour_guide')},
            },
        ),
    ]
